name: Test Install

on: [push, pull_request]

jobs:
  conda-install-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          use-mamba: true
          channels: conda-forge,bioconda
          python-version: 3.12.9

      - name: Create environment and run install.sh
        shell: bash -l {0}
        run: |
          bash install.sh For_Linux_user.yml

      - name: Verify installation
        shell: bash -l {0}
        run: |
          conda activate splice-decoder
          which bedtools
          which cpat
          python -c "import Bio; print(Bio.__version__)"
